name: "Push Build to Jfrog Artifactory 🐸"
run-name: ${{ github.actor }} push to jfrog 🐸
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  inputs:
    logLevel:
      description: 'Log level'
      required: true
      default: 'warning'
      type: choice
      options:
      - info
      - warning
      - debug
jobs:
 build:
  runs-on: ubuntu-latest
  
  steps:
  # This action checks out the code from the repository
  - name: Checkout Code
    uses: actions/checkout@v2
  - uses: jfrog/setup-jfrog-cli@v4
  - run: jf --version
