name: Create envfile

on: [ push ]
permissions: read-all|write-all

jobs:

  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "credentials.json"
        json: ${{ secrets.DUMB_SECRET }}
