name: Create envfile

on: [ "push", "workflow_dispatch", "pull_request" ]
permissions: 
  actions: none
  checks: read
  contents: read

jobs:
  create-file-from-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "credentials.json"
        json: ${{ secrets.DUMB_SECRET }}
